# Вторая лабораторная работа

Обработка пропусков в данных, кодирование категориальных признаков и масштабирование

In [ ]:
!pip install scikit-learn pandas numpy seaborn matplotlib

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Я буду использовать готовый датасет Titanic

In [2]:
df = sns.load_dataset('titanic')

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Колонку deck можно просто удалить, так как там слишком много пропусков. Строки с embarked тоже можно удалить, так как там слишком мало пропусков.

In [4]:
clear = df.drop(columns=['deck']).dropna(subset=['embark_town', 'embarked'])
clear.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

В колонке age мы заменил возраст на медианный.

In [5]:
clear['age'] = clear['age'].fillna(clear['age'].median())
clear.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

От пропусков избавились. Переходим к кодированию категориальных признаков.

In [6]:
clear.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    str
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     889 non-null    str
 8   class        889 non-null    category
 9   who          889 non-null    str
 10  adult_male   889 non-null    bool
 11  embark_town  889 non-null    str
 12  alive        889 non-null    str
 13  alone        889 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 86.1 KB

Закодируем пол и одиночество как 0 и 1.

In [7]:
clear['sex'] = clear['sex'].map({'male': 0, 'female': 1})
clear['alone'] = clear['alone'].map({False: 0, True: 1})
clear.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    int64
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     889 non-null    str
 8   class        889 non-null    category
 9   who          889 non-null    str
 10  adult_male   889 non-null    bool
 11  embark_town  889 non-null    str
 12  alive        889 non-null    str
 13  alone        889 non-null    int64
dtypes: bool(1), category(1), float64(2), int64(6), str(4)
memory usage: 92.2 KB

Колонки alive, who, embark_town и adult_male можно выкинуть, так как они дублируют уже существующие признаки.

In [8]:
clear.drop(columns=['alive','who','adult_male', 'embark_town'], inplace=True)
clear.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    int64
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    str
 8   class     889 non-null    category
 9   alone     889 non-null    int64
dtypes: category(1), float64(2), int64(6), str(1)
memory usage: 70.5 KB

Класс мы закодируем от 1 до 3, так как его можно упорядочить.

In [9]:
clear['class'] = clear['class'].map({'First': 1, 'Second': 2, 'Third': 3}).astype(int)
clear.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    int64
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    str
 8   class     889 non-null    int64
 9   alone     889 non-null    int64
dtypes: float64(2), int64(7), str(1)
memory usage: 76.4 KB

Закодируем one-hot колонку embarked

In [10]:
embarked_dummies = pd.get_dummies(clear['embarked'], prefix='embarked')
embarked_dummies = embarked_dummies.astype(int)
clear = pd.concat([clear, embarked_dummies], axis=1)
clear = clear.drop('embarked', axis=1)
clear.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    889 non-null    int64
 1   pclass      889 non-null    int64
 2   sex         889 non-null    int64
 3   age         889 non-null    float64
 4   sibsp       889 non-null    int64
 5   parch       889 non-null    int64
 6   fare        889 non-null    float64
 7   class       889 non-null    int64
 8   alone       889 non-null    int64
 9   embarked_C  889 non-null    int64
 10  embarked_Q  889 non-null    int64
 11  embarked_S  889 non-null    int64
dtypes: float64(2), int64(10)
memory usage: 90.3 KB

Масштабируем данные.

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

clear_scaled = pd.DataFrame(scaler.fit_transform(clear.drop('survived', axis=1)))

clear_scaled.describe()

,0,1,2,3,4,5,6,7,8,9,10
count,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000,889.000000
mean,0.655793,0.350956,0.363096,0.065523,0.063742,0.062649,0.655793,0.601800,0.188976,0.086614,0.724409
std,0.417350,0.477538,0.163168,0.137963,0.134460,0.097003,0.417350,0.489803,0.391710,0.281427,0.447063
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.500000,0.000000,0.271174,0.000000,0.000000,0.015412,0.500000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.346569,0.000000,0.000000,0.028213,1.000000,1.000000,0.000000,0.000000,1.000000
75%,1.000000,1.000000,0.434531,0.125000,0.000000,0.060508,1.000000,1.000000,0.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000